### ISSUE TITLE
Allow for tolerance with "participantRef"

### ISSUE THREAD

**Issue by yT0n1** [jan-ladleif/chor-js#45]
Some files from external sources might contain "participantRef" instead of "participantRefs". 

The standard is unclear regarding this. See pages 322 and 364 in the standard. BPMN20.cmof and Semantic.xsd differ in that regard (https://www.omg.org/spec/BPMN/#docs-normative-supporting). Import should support both options, export should support "participantRef" to be compatible with eclipse and Signavio

**Comment by jan-ladleif** [comment]
Here's the relevant replacement snippet from another project of mine for the import:

```javascript
// Preprocessing: Signavio exports <participantRef> elements instead of
// <participantRefs> (notice the missing 's'). The metamodel expects the s, though.
xml = xml.replace(/<(\/)?(bpmn2:|bpmn:)?participantRef>/g, '<$1$2participantRefs>');
```

**Comment by jan-ladleif** [comment]
This has been fixed in bpmn-moddle with https://github.com/bpmn-io/bpmn-moddle/pull/60

We should just update and use the `participantRef` variant now. There are probably no models around that use the version with the `s`.
